[package]
name = "charoite"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "charoite"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0"
urlencoding = "2.1"
clap = { version = "4.0", features = ["derive"] }
